title: UniCAVE
description: A Unity3D Plugin for Non-Head Mounted Virtual Reality Display Systems
author: Virtual Environments group, Wisconsin Institute for Discovery
locale: en_US
theme: minima
baseurl: /UniCAVE
url: https://widve.github.io